server:
  port: 8002


eureka:
  #server: #取消自我保护机制  ，不建议使用
    #enable-self-preservation:  false
  instance:
    hostname: eureka8003.com  #eureka 的服务端的实例名称
  client:
    register-with-eureka: false     # 表示自己不想注册中进行注册自己      
    fetch-registry:  false  #表示自己就是注册中心，就维护服务实例的，不需要进行检索服务
    service-url:
     defaultZone: http://localhost:8002/eureka/         #设置Eureka server  互交的地址，查询服务注册中心都需要这个地址
      #defaultZone: http://10.0.0.90:8002/eureka/,http://10.0.0.53:8003/eureka/
     
     

       
       
