server:
  port: 8015

eureka:
  #server: #取消自我保护机制  ，不建议使用
    #enable-self-preservation:  false
  instance:
    hostname: eureka8001.com  #eureka 的服务端的实例名称
    prefer-ip-address: true
  client:
    register-with-eureka: true     # 表示自己不想注册中进行注册自己      
    fetch-registry:  true  #表示自己就是注册中心，就维护服务实例的，不需要进行检索服务
    service-url:
      defaultZone: http://192.168.1.5:8015/eureka/
      #defaultZone: eureka8002.com:8002/eureka/             #设置Eureka server  互交的地址，查询服务注册中心都需要这个地址
     

       
       
