server:
  port: 8013

# service registry
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://10.190.60.4:8002/eureka/


# data source
spring:
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource  #连接数据库源的类型
    #    driver-class-name:  com.mysql.jdbc.Driver #mysql的驱动包
    #    url:  jdbc:mysql://localhost:3306/ktmcloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true    #连接数据库的名称
    #    username: root
    #    password: root
    #    dbcp2:
    #      min-idle:  6  #连接池最小的连接数
    #      initial-size: 6  #初始化的连接数
    #      max-idle: 6  #最大连接数
    #      max-wait-millis: 200  #等待获取最大超时时间
    #type: com.alibaba.druid.pool.DruidDataSource  #连接数据库源的类型
    url: jdbc:mysql://10.190.60.4:3306/cdfdb?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username: root
    password: cdf123
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false



redis:
  # Redis数据库索引（默认为0）
  DEFAULT_DB_INDEX: 0
  # Redis服务器地址  ygl服务器地址
  HOST_IP: 159.75.130.15
  # Redis服务器连接端口
  HOST_PORT: 6380
  # Redis服务器连接密码（默认为空）
  PASSWORD: 123456
  # 连接池最大连接数（使用负值表示没有限制）
  MAX_TOTAL: 8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  MAX_WAIT_MILLS: -1
  # 连接池中的最大空闲连接
  MAX_IDLE: 8



# mybatis conf
mybatis:
  #config-location:  classpath:mybatis/mybatis.cfg.xml   #mybatis配置文件的路径加载
  type-aliases-package: cn.com.ktm.mt.model.entity  #加载所有实体类的路径
  mapper-locations:
    - classpath:/mapper/**/*.xml   #映射mapper所有的文件
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    default-fetch-size: 100
    default-statement-timeout: 30
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #这个是可以打印sql、参数、查询结果的
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000



ribbon:
  eureka:
    enabled: true
  ReadTimeout: 9000


mapper:
  notEmpty: true

logging:
  config: classpath:log4j2.yml


tx-lcn:
  client:
    manager-address:127.0.0.1:8070

INF_URL :
  http://q.hl95.com:8061
noticename :
  xablyyzm
password:
  xablyyzm123
epid:
  126643

#科玛接口有关
kema:
  interface: "https://m.cdfgsy.cn"
